const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  listPorts: () => ipcRenderer.invoke("list-ports"),
  connectPort: (portName) => ipcRenderer.invoke("connect-port", portName),
  disconnectPort: () => ipcRenderer.invoke("disconnect-port"),
  sendData: (msg) => ipcRenderer.invoke("send-data", msg),
  setInterval: (interval) => ipcRenderer.invoke("set-interval", interval),
  getInterval: () => ipcRenderer.invoke("get-interval"),
  setProtocol: (protocol) => ipcRenderer.invoke("set-protocol", protocol),
  setFTPHost: (host) => ipcRenderer.invoke("set-ftp-host", host),
  setFTPPort: (port) => ipcRenderer.invoke("set-ftp-port", port),
  setFTPUser: (user) => ipcRenderer.invoke("set-ftp-user", user),
  setFTPPassword: (password) => ipcRenderer.invoke("set-ftp-password", password),
  getFTPConfig: () => ipcRenderer.invoke("get-ftp-config"),
  setMQTTBroker: (broker) => ipcRenderer.invoke("set-mqtt-broker", broker),
  setMQTTPort: (port) => ipcRenderer.invoke("set-mqtt-port", port),
  setMQTTUser: (user) => ipcRenderer.invoke("set-mqtt-user", user),
  setMQTTPassword: (password) => ipcRenderer.invoke("set-mqtt-password", password),
  setMQTTSSL: (enabled) => ipcRenderer.invoke("set-mqtt-ssl", enabled),
  uploadMQTTCert: (type, fileData) => ipcRenderer.invoke("upload-mqtt-cert", { type, fileData }),
  getMQTTConfig: () => ipcRenderer.invoke("get-mqtt-config"),
  setHTTPURL: (url) => ipcRenderer.invoke("set-http-url", url),
  setHTTPAuth: (auth) => ipcRenderer.invoke("set-http-auth", auth),
  getHTTPConfig: () => ipcRenderer.invoke("get-http-config"),
  uploadFile: (filename) => ipcRenderer.invoke("upload-file", filename),
  setTCPHost: (host) => ipcRenderer.invoke("set-tcp-host", host),
  setTCPPort: (port) => ipcRenderer.invoke("set-tcp-port", port),
  getTCPConfig: () => ipcRenderer.invoke("get-tcp-config"),
  onSerialData: (callback) => ipcRenderer.on("serial-data", (event, data) => callback(data)),
});